### ISSUE TITLE
Output of SimpleSnippetsList is not formatted properly

### ISSUE THREAD

**Issue by ghid** [andreyorst/SimpleSnippets.vim#44]
**Describe the bug**
The output of `SimpleSnippetsList` is distorted on Windows.

**Steps to reproduce**
Submit `:SimpleSnippetList` on the Vim command line

**Expected behavior**
Display a well formed list of the available snippets.

**Actual behavior**
Due to the use of Linux version of the `echo` command the output on windows is not well formatted. Also backups of snippets (ending with `~`) are displayed. IMO backup files should be suppressed in output.

**Screenshot or gif** (if possible)
![simplesnippets_issuex_1](https://user-images.githubusercontent.com/7606219/41084901-aea60ac6-6a35-11e8-80bb-a299b0b43083.gif)

**Environment:**
 - OS: Windows 10
 - Vim version: VIM - Vi IMproved 8.1 (2018 May 17, compiled Jun  7 2018 08:35:40) / MS-Windows 64-bit GUI version / Included patches: 1-37
 - This plugin version: ac4d64eb1ead5cc13d75a3c7f9b3549bb1ddc4cc

btw: Thanks a lot for implementing `SimpleSnippetsEditDescriptions` . Work's great 👍

**Comment by andreyorst** [comment]
oh... Well that's unexpected. I don't have windows right now... Not sure that I can install it without license. I'll think what I can do.

**Comment by andreyorst** [comment]
As for backups, Is this a windows only behaviour? Newer saw them actually in Linux.

**Comment by ghid** [comment]
The backup files are generated because of my vim settings; I think I can fix that problem by my own. Sorry, I haven't investigated in advance. See `:help 'writebackup'`, `:help 'backup'` and `:help 'backupext'` for more details.

A suggestion for the `echo` problem: Maybe it is possible to configure in global variable which command should be used (e.g. `echo -n` for Linux and `echo` for windows). Eventually an additional setting for the line break is neccessary.

**Comment by andreyorst** [comment]
> See :help 'writebackup', :help 'backup' and :help 'backupext' for more details.

Ah, ok. I think I'll add ignoring of backups.

> A suggestion for the echo problem: Maybe it is possible to configure in global variable which command should be used (e.g. echo -n for Linux and echo for windows). Eventually an additional setting for the line break is neccessary.

I'm thinking to use vim's own `echo` instead of system. It will be lot more portable.

**Comment by andreyorst** [comment]
@ghid please try latest master

**Comment by ghid** [comment]
Looks good!

![image](https://user-images.githubusercontent.com/7606219/41094286-11fd9efa-6a4e-11e8-9baf-9db01c6cf0ac.png)

Thanks a lot 👍

**Comment by andreyorst** [comment]
On a bad side line numbers are gone. because it was system call too. But I never feel like actual usefulness of them in fact.

**Comment by andreyorst** [comment]
@ghid sorry to disturb you but i was wondering what software are you using to create gifs of your screen on windows? They are so clean, and still manageable sized

**Comment by ghid** [comment]
Hey @andreyorst , I used https://www.screentogif.com/ for recording the gifs - and you're not disturbing me 😉

**Comment by andreyorst** [comment]
> The backup files are generated because of my vim settings;

@ghid This should not be the issue anymore.
