### ISSUE TITLE
'$n's somewhere in the text are confusing to SimpleSnippets

### ISSUE THREAD

**Issue by ghid** [andreyorst/SimpleSnippets.vim#45]
if '$_n_'s appear somewhere in the file they're disturbing for snippets.

I've got that code somewhere in my file:
```ahk
		GetLongMatch() {
			_log := new Logger("class." A_ThisFunc)

			RegExMatch(this.stExpr, "^([imsxADJUXPSC]+\))?(.*)", $)
			if (_log.Logs(Logger.Finest)) {
				_log.Finest("this.stExpr", this.stExpr)
				_log.Finest("$1", $1)
				_log.Finest("$2", $2)
			}
			
			return _log.Exit($1 "^--" (this.iFlags & OptParser.OPT_NEG ? "(no-?)?" : "") $2 "$")
		}
```

if I expand a snippet elsewhere it produces unwanted content:

![simplesnippets_issue](https://user-images.githubusercontent.com/7606219/41895910-7cef62be-7923-11e8-9912-460b56f17d4d.gif)

The `if` snippet used in the example above looks like this:
```
if (${1:true}) {
	${0:; TODO: Add code}
}
```

Question: Is it possible to distinct between '$_n_'s within the snippet and the rest of the file to avoid that behaviour? If  not, a remark in the documentation would be helpfull. _(I hope I haven't overseen this..._ 😨)
If I replace the `$` in my code, for example by an `X`, everything works fine what is a sufficient workaround for me. But I _love_ your plugin and would like it to be as efficient as possible, so I opened this issue.

**Environment:**
 - OS: Windows 10
 - gVim version: VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun 26 2018 07:57:14) / MS-Windows 64-bit GUI version / Included patches: 1-116
 - This plugin version: a4145797c038231ff8c09c60f8ec34c305b24f9f

**Comment by andreyorst** [comment]
I see, that's strange, the search IS restricted to snippet area. Maybe some cursor positioning is not right. I'll see

**Comment by andreyorst** [comment]
This should be fixed now. The problem was in function that searches for placeholders in whole file before snippet was parsed.

**Comment by andreyorst** [comment]
Also I'd mention that this still will make some troubles if snippet will be expanded on the same with `$N`, like
```
_log.Finest("$1", $1) if|
```
where `|` is cursor, as usual
