### ISSUE TITLE
Integrate SimpleSnippets with "supertab" plugin?

### ISSUE THREAD

**Issue by KKPMW** [andreyorst/SimpleSnippets.vim#47]
I am currently using snipmate and would like to move to something simpler like this plugin.

However in my setup snipmate has one advantage - it be default works with [supertab](https://github.com/ervandew/supertab) plugin which let's use tab for multiple purposes (keyword completion as well as snippet expansion).

Are there any plans to integrate SimpleSnippets with supertab?

**Comment by andreyorst** [comment]
I'm not using Supertab personally, but I'm do not mind to add Supertab support. But I don't know how its implemented. If it is implemented on snipMate side, then there is no problem. However if it is implemented on the Supertab side, that may cause some problems. But I'll try to do my best.

Apparently I've tried to integrate SimpleSnippets in YCM, and it is done at YCM side. I've succeeded, however I couldn't get responsefromproject maintainers, so I've dropped the idea.

**Comment by KKPMW** [comment]
Thanks for taking an interest in this.

I am not sure about implementation, but after some reading it seems in the case of snipmate it was implemented at the snipmate's side. This seems like the relevant file from their repo: https://github.com/garbas/vim-snipmate/blob/master/after/plugin/snipMate.vim

Note that this is a separate fork of snipmate which seems to (in part) be created in order to address the supertab compatibility.

**Comment by andreyorst** [comment]
> Note that this is a separate fork of snipmate which seems to (in part) be created in order to address the supertab compatibility.

It is "official" fork. They forked snipmate because the developing was stopped by the author. And this is stated in msanders's repo.

> I am not sure about implementation, but after some reading it seems in the case of snipmate it was implemented at the snipmate's side.

This is good. I'll check it

**Comment by andreyorst** [comment]
Sorry I've misunderstood the point of the issue. I thought by __integrate with supertab__ you've meant to show snippets in supertab's completion popup. But as for tab mapping you can just use custom function:
```vim
function! ExpandOrComplete()
	if SimpleSnippets#isExpandableOrJumpable()
		return "\<Esc>:call SimpleSnippets#expandOrJump()\<Cr>"
	else
		return "\<C-n>"
	endif
endfunction
```
And then just map it to your <key>Tab</key>:
```vim
inoremap <silent><Tab> <C-r>=ExpandOrComplete()<CR>
```

Or just use an `<expr>` mapping:
```vim
inoremap <silent><expr><Tab> SimpleSnippets#isExpandableOrJumpable() ? "\<Esc>:call SimpleSnippets#expandOrJump()\<Cr>" : "\<C-n>"
```
I'm not sure about `<C-n>` part, maybe you should use `<Plug>SuperTabForward` or something like that. But the idea is that you can do it without integration. There are ton of completion plugins, if I start adding all of them into the plugin, there will be total mess of "default" mappings, which will not suit every one anyway.

Does this solves your problem?

**Comment by KKPMW** [comment]
Yes this addresses it. I am trying to make it work with partial luck for now, have to read some docs from supertab as well.

The issue was about integration in any case, so if you think this is not something that should be added to this plugin - the ticket should be closed.

Thanks a lot for your time an answers!

**Comment by andreyorst** [comment]
If supertab can't display completions from different sources, (afaik it can't), there is no integration possible. However I don't mind to help with mappings, and later this can be included to documentation.
